/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_edd;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Crearsuario
     * 
     */
    static LinkedList<Usuario> usuarios;
    static Usuario usuario;
    
    public CrearUsuario(Usuario usuario, LinkedList<Usuario> usuarios) {
        this.usuarios=usuarios;
        this.usuario=usuario;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        LabelApodo = new javax.swing.JLabel();
        txtApodo = new javax.swing.JTextField();
        LabelDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        LabelTitulo2 = new javax.swing.JLabel();
        LabelPSN = new javax.swing.JLabel();
        txtPSN = new javax.swing.JTextField();
        LabelSteam = new javax.swing.JLabel();
        txtSteam = new javax.swing.JTextField();
        LabelNSwitch = new javax.swing.JLabel();
        LabelTwitter = new javax.swing.JLabel();
        txtNSwitch = new javax.swing.JTextField();
        txtTwitter = new javax.swing.JTextField();
        LabelXbox = new javax.swing.JLabel();
        LabelDiscrod = new javax.swing.JLabel();
        txtXbox = new javax.swing.JTextField();
        txtDiscord = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(746, 483));

        LabelTitulo.setText("Crear/Modificar Usuario");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        LabelNombre.setText("Nombre:");

        LabelApodo.setText("Apodo:");

        txtApodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApodoActionPerformed(evt);
            }
        });

        LabelDescripcion.setText("Descripción:");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        LabelTitulo2.setText("Redes Sociales y demás:");

        LabelPSN.setText("PSN-ID");

        LabelSteam.setText("Link a cuenta Steam");

        txtSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSteamActionPerformed(evt);
            }
        });

        LabelNSwitch.setText("Codigo de Amigo Nintendo Switch");

        LabelTwitter.setText("Link a cuenta Twitter");

        LabelXbox.setText("Xbox GamerTag");

        LabelDiscrod.setText("Discord");

        txtXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXboxActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 204, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnImagen.setText("Seleccionar imagen de perfil");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelApodo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                            .addComponent(LabelNombre, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(LabelTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelTitulo2)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelPSN)
                            .addComponent(LabelNSwitch)
                            .addComponent(LabelXbox)
                            .addComponent(txtPSN)
                            .addComponent(txtNSwitch)
                            .addComponent(txtXbox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelSteam)
                            .addComponent(LabelTwitter)
                            .addComponent(LabelDiscrod)
                            .addComponent(txtSteam)
                            .addComponent(txtTwitter)
                            .addComponent(txtDiscord, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTitulo)
                    .addComponent(LabelTitulo2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelSteam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelTwitter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelDiscrod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiscord))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelPSN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelNSwitch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelXbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtXbox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnImagen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelApodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApodoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXboxActionPerformed
    private void volver(){
        
        Menu menu = new Menu(usuarios);
        menu.setVisible(true);
        this.dispose();
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        usuario.setsApodo(txtApodo.getText());
        usuario.setsNombre(txtNombre.getText());
        usuario.setsDescripcion(txtDescripcion.getText());
        usuario.setsPSN(txtPSN.getText());
        usuario.setsNSFCode(txtNSwitch.getText());
        usuario.setsXboxGT(txtXbox.getText());
        usuario.setsSteam(txtSteam.getText());
        usuario.setsTwitter(txtTwitter.getText());
        usuario.setsDiscord(txtDiscord.getText());
        
        insertionSort(usuarios);
        volver();
      
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSteamActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        String sImagen;
        File imagen = new File("");
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo = fc.getSelectedFile();
        
        try{
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            
            String texto="";
            String linea="";
            
            while((linea=br.readLine())!=null){
                texto+=linea;
            }
            imagen = fc.getSelectedFile();
            sImagen=(imagen.getParent()+"\\"+imagen.getName());
            ImageIcon iImagen = new ImageIcon(sImagen);
            usuario.iImagen.setImage(iImagen.getImage());
            JOptionPane.showMessageDialog(null, "Se ha seleccionado una imagen","Estado",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario(usuario,usuarios).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelApodo;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelDiscrod;
    private javax.swing.JLabel LabelNSwitch;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPSN;
    private javax.swing.JLabel LabelSteam;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTitulo2;
    private javax.swing.JLabel LabelTwitter;
    private javax.swing.JLabel LabelXbox;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDiscord;
    private javax.swing.JTextField txtNSwitch;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPSN;
    private javax.swing.JTextField txtSteam;
    private javax.swing.JTextField txtTwitter;
    private javax.swing.JTextField txtXbox;
    // End of variables declaration//GEN-END:variables
        
        public static void insertionSort(LinkedList<Usuario> datos){
            for(int i=0;i<datos.size();i++){
                Usuario temp = datos.get(i); //Valor a insertar
                int insP = i; //Posicion donde vamos a insertar
                for(int prev = i - 1;prev>=0;prev--){//Busca donde insertar
                    if(datos.get(prev).getsApodo().compareTo(temp.getsApodo()) > 0){
                        datos.set(insP,datos.get(prev));//datos.set(insP, datos.get(prev));//movemos valor de prev a la posición insP
                        insP--;//retrocede una posicion
                        
                    }else{
                        break;
                    }
                }
                datos.set(insP, temp) ;//= temp; //Insertamos
            }
        }
}
