/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_edd;

import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class VerUsuario extends javax.swing.JFrame {

    MetodosExtra metodo = new MetodosExtra();
    static LinkedList<Usuario> usuarios;
    static Usuario usuario;
    
    /**
     * Creates new form UP
     */
    public VerUsuario(Usuario usuario,LinkedList<Usuario> usuarios) {
        this.usuarios = usuarios;
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        LabelImagen.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        btnTwitter = new javax.swing.JButton();
        btnSteam = new javax.swing.JButton();
        btnPSN = new javax.swing.JButton();
        btnNintendo = new javax.swing.JButton();
        LabelImagen = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        LabelDescripcion = new javax.swing.JLabel();
        LabelNombreR = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnDiscord = new javax.swing.JButton();
        btnXbox = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil de "+usuario.getsApodo());
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        btnTwitter.setBackground(new java.awt.Color(255, 255, 255));
        btnTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_edd/Iconos/Twitter.png"))); // NOI18N
        btnTwitter.setText("Twitter");
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });

        btnSteam.setBackground(new java.awt.Color(255, 255, 255));
        btnSteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_edd/Iconos/Steam.png"))); // NOI18N
        btnSteam.setText("Steam");
        btnSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSteamActionPerformed(evt);
            }
        });

        btnPSN.setBackground(new java.awt.Color(255, 255, 255));
        btnPSN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_edd/Iconos/PlayStation.png"))); // NOI18N
        btnPSN.setText("PSN");
        btnPSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPSNActionPerformed(evt);
            }
        });

        btnNintendo.setBackground(new java.awt.Color(255, 255, 255));
        btnNintendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_edd/Iconos/Nintendo Switch.png"))); // NOI18N
        btnNintendo.setText("Nintendo");
        btnNintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNintendoActionPerformed(evt);
            }
        });

        LabelImagen.setIcon(usuario.iImagen);
        LabelImagen.setText("Imagen");

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelUsuario.setText(usuario.getsApodo());

        LabelDescripcion.setBackground(new java.awt.Color(0, 51, 255));
        LabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescripcion.setText(usuario.getsDescripcion());
        LabelDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción del jugador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        LabelNombreR.setText(usuario.getsNombre());

        btnSalir.setText("Volver al Menú");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnDiscord.setBackground(new java.awt.Color(255, 255, 255));
        btnDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_edd/Iconos/Discord.png"))); // NOI18N
        btnDiscord.setText("Discord");
        btnDiscord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscordActionPerformed(evt);
            }
        });

        btnXbox.setBackground(new java.awt.Color(255, 255, 255));
        btnXbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_edd/Iconos/Xbox.png"))); // NOI18N
        btnXbox.setText("Xbox");
        btnXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelUsuario)
                            .addComponent(LabelNombreR)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnTwitter)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSteam)
                            .addComponent(btnDiscord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNintendo))
                    .addComponent(LabelDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNombreR))
                    .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTwitter)
                    .addComponent(btnSteam)
                    .addComponent(btnPSN)
                    .addComponent(btnNintendo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiscord)
                    .addComponent(btnXbox))
                .addGap(27, 27, 27)
                .addComponent(LabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
    metodo.enlace(usuario.getsTwitter());        
    }//GEN-LAST:event_btnTwitterActionPerformed

    private void btnSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSteamActionPerformed
    metodo.enlace(usuario.getsSteam());
    }//GEN-LAST:event_btnSteamActionPerformed

    private void btnPSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPSNActionPerformed
        JOptionPane.showMessageDialog(jMenu1, "PSN ID:\n"+usuario.getsPSN(), "PSN ID", WIDTH);
    }//GEN-LAST:event_btnPSNActionPerformed

    private void btnNintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNintendoActionPerformed
        JOptionPane.showMessageDialog(jMenu1, "Código de amigo Nintendo Switch: \n"+usuario.getsNSFCode(), "Nintendo Switch Friend Code:", WIDTH);
    }//GEN-LAST:event_btnNintendoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Menu menu = new Menu(usuarios);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDiscordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscordActionPerformed
        JOptionPane.showMessageDialog(jMenu1, "Nombre de usuario: \n"+usuario.getsDiscord(), "Código de usuario Discord:", WIDTH);
    }//GEN-LAST:event_btnDiscordActionPerformed

    private void btnXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXboxActionPerformed
        JOptionPane.showMessageDialog(jMenu1, "Xbox GamerTag: \n"+usuario.getsXboxGT(), "Xbox GamerTag:", WIDTH);
    }//GEN-LAST:event_btnXboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUsuario(usuario, usuarios).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelImagen;
    private javax.swing.JLabel LabelNombreR;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JButton btnDiscord;
    private javax.swing.JButton btnNintendo;
    private javax.swing.JButton btnPSN;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSteam;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JButton btnXbox;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    // End of variables declaration//GEN-END:variables
}
